version: 2.1
orbs:
  singularity: singularity/singularity@1.0.10
jobs:
  sbuild:
    executor: singularity/machine
    steps:
      - checkout
      - singularity/install-go:
          go-version: '1.13'
      - singularity/debian-install-3:
          singularity-version: 3.5.0
      - singularity/build-image:
          from-uri: src/ophys_etl/transforms/suite2p_container.def
          image: suite2p_container.img
workflows:
  install_debian_3_example:
    jobs:
      - sbuild
