version: 2.1
orbs:
  singularity: singularity/singularity@1.0.10
jobs:
  sbuild:
    executor: singularity/machine
    steps:
      - checkout
      - singularity/install-go:
          go-version: '1.13'
      - singularity/debian-install-3:
          singularity-version: 3.5.0
      - run:
          # copied from singularity/build-image to add branch-specific build
          name: Build Singularity Container
          command: |
            NOSUDO=false
            which sudo || NOSUDO=true
            if [[ "$NOSUDO" == "false" ]]; then
                if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
            fi
            if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi
            $SUDO SINGULARITYENV_OPHYS_ETL_TAG=${CIRCLE_BRANCH} singularity build suite2p_container.img src/ophys_etl/transforms/suite2p_container.def
      - run:
          name: Run Singularity Container
          command: |
            singularity run ./suite2p_container.img python -m ophys_etl.suite2p_wrapper --help
workflows:
  install_debian_3_example:
    jobs:
      - sbuild
